# Numpy随堂练习1

## 1. 导入numpy库并简写为 np (★☆☆)

(提示: import … as …)

In [1]:
import numpy as np

## 2. 创建一个长度为10的空向量 (★☆☆)

(提示: np.zeros)

In [6]:
array = np.zeros((10))
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 3. 创建一个长度为10的空向量，并将其第五个值置为1 (★☆☆)

(提示: array[4] = 1)

In [7]:
array[4] = 1

## 4. 创建一个值域范围从10到49的向量(★☆☆)

(提示: np.arange)

In [11]:
ten_to_fourtynine = np.arange(10, 50)
# 左闭右开 
ten_to_fourtynine

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 5. 反转一个向量(第一个元素变为最后一个) (★☆☆)

(提示: array[::-1])

In [12]:
ten_to_fourtynine[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 6. 创建一个 3x3 并且值从0到8的矩阵(★☆☆)

(提示: reshape)

In [13]:
matrix = np.arange(0,9).reshape((3,3))
matrix

## 7. 创建一个 3x3 的单位矩阵 (★☆☆)

(提示: np.eye)

In [14]:
eye_3x3 = np.eye(3)
eye_3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 8. 创建一个 3x3x3的随机数组 (★☆☆)

(提示: np.random.random)

In [15]:
np.random.random((3,3,3))

array([[[0.61071064, 0.68876304, 0.86610807],
        [0.61636257, 0.81535875, 0.87091668],
        [0.5662866 , 0.74805126, 0.00286644]],

       [[0.76406279, 0.39369442, 0.59079264],
        [0.26630744, 0.25019208, 0.54177891],
        [0.07295355, 0.98446016, 0.35241535]],

       [[0.98927315, 0.59052467, 0.69691773],
        [0.82509201, 0.22032679, 0.77018514],
        [0.93507302, 0.72035251, 0.00806708]]])

## 9. 创建一个长度为10的等间隔向量，其值域范围从0到1，但是不包括0和1 (★★☆)

(提示: 利用np.linspace将0到1分隔成12份，再用切片的方法掐头去尾)

In [19]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

## 10. 如何读取以下文件? (★★☆)

(提示: np.genfromtxt)

1, 2, 3, 4, 5

6,  ,  , 7, 8

 ,  , 9,10,11

In [22]:
np.genfromtxt('./T10.txt', delimiter = ',')

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

## 利用Numpy操作图像

In [23]:
import matplotlib.pyplot as plt
import numpy as np
pic = plt.imread('images/WhiteSnake.jpg')
plt.imshow(pic)
plt.show()

**试着利用索引和切片显示图像的一部分吧**